feat(): added branching information
antstackio/Employee-Hand-Book pull request #3
Opened 2023-04-06 17:43 UTC by sandykumar93

- added branching 101 section
- updated hyperlinks and readme

2023-04-08 05:52 UTC, vishwasnavadak requested changes

2023-04-08 05:52 UTC, vishwasnavadak commented on branching-101/branch-naming-convention.md
> +{issue-type}/{jira/linear-ticket-number}-{short-description}
Mention issue types and examples.

2023-04-08 05:52 UTC, vishwasnavadak commented on branching-101/branch-rules.md
> +- Do not allow bypassing the above settings ⛔.
We could attach screenshots, just to avoid confusion

2023-04-10 07:32 UTC, sandykumar93 commented on branching-101/branch-naming-convention.md
> +{issue-type}/{jira/linear-ticket-number}-{short-description}
done

2023-04-10 07:33 UTC, sandykumar93 commented on branching-101/branch-rules.md
> +- Do not allow bypassing the above settings ⛔.
done

2023-04-10 10:36 UTC, vishwasnavadak approved these changes

2023-04-10 10:36 UTC, merged